---
# tasks file for lamp
# Author: Sylvain Ake
# Email: akesylvain@gmail.com
# Date: May 2024
- name: "Update repository"
  apt:
     update_cache: yes

- name: "[LAMP] Install LAMP"
  apt:
     name: "{{ item }}"
     state: latest
  with_items:
     - apache2
     - mysql-server
     - php
     - libapache2-mod-php
     - php-cli
     - php-cgi
     - php-mysql
     - php-mysqli
     - wget

- name: "Start Apache Service and MySQL"
  service:
     name: "{{ item }}"
     state: started
     enabled: yes
  with_items:
     - apache2
     - mysql

- name: "Install Python"
  apt: 
    name: "{{ item }}" 
    state: present
  with_items:
      - python3
      - python3-pip
      - mysql-client
      - libmysqlclient-dev

- name: "Install PyMySQL"
  pip:
    name: pymysql
    state: present


- name: "Create Database"
  mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "wordpdb"
    state: present

- name: "Create database user"
  mysql_user:
     login_unix_socket: /var/run/mysqld/mysqld.sock
     name: "wordu"
     password: "space123"
     priv: "*.*:ALL"
     host: 'localhost'
     state: present
